### PR TITLE
Fix RegExp.lastMatch on Firefox when it is undefined

### PR DESCRIPTION
**Pull request by mweibel**
I came accross the issue that sometimes in Firefox `RegExp.lastMatch` is undefined and then the `createRegExpRestore()` Function fails. 

I hope the tests run properly, I couldn't test the Saucelabs tests because of not having an account.

### CODE REVIEW

**Comment by andyearnshaw** [comment]
Change looks harmless enough.  Tests are still failing on SL because of unrelated issues that I haven't had chance to resolve yet.

**Comment by mweibel** [comment]
Perfect, thanks!

**Comment by slorber** [comment]
Hi,

Has this been released yet?

**Comment by caridy** [comment]
not yet, will be in 1.0.0-rc1, still working on that.

**Comment by jsg2021** [comment]
I think you can work around it by doing `/./.test(' ');` somewhere early in your app before importing this library

**Pull request merged**
