### PR TITLE
Updated to CLDR 28.0.0

### PR DESCRIPTION
**Pull request by mdehoog**
Steps taken:
1. Updated package.json CLDR dependencies from `^27.0.3` to `^28.0.0`.
2. `npm install`
3. `grunt cldr`
4. `grunt`

### CODE REVIEW

**Comment by rtymchyk** [comment]
Would love to get this merged. It's not clear how I can actually review this though. Is there something to look for?

**Comment by caridy** [comment]
@rtymchyk I plan to release a new version next thrusday, based off https://github.com/andyearnshaw/Intl.js/pull/146, I can pull in CLDR version 28 as part of it.

**Comment by rtymchyk** [comment]
That would be great, thank you.

**Comment by caridy** [comment]
+ intl@1.1.0

**Pull request closed without merging**
