### PR TITLE
Shorten restore regexes

### LINKED ISSUE #196: createRegExpRestore throws an error when RegExp.lastMatch is long
We're running into an issue with createRegExpRestore generating expressions that are over the size limit.  As createRegExpRestore is generating an expression based on RegExp.lastMatch, when the last matching string was extremely long, the expression generated was therefore too long and caused an error to be thrown.

We've been kicking this around here at work, and suspect that there may not be a perfect solution to the problem of needing to restore the RegExp static properties after interacting with regular expressions.  To that end, I'm proposing that we make this behavior optional - I'll be sending a PR for this.

### PR DESCRIPTION
**Pull request by mtlewis**
Fixes #196.

@nosilleg and I spent some time on this today, and incorporated suggestions from #196 to improve the way createRegExpRestore works.  The ability to disable cache/restore of regexes is still there, but the regexes generated now use [\s\S]{n} in conjunction with lastIndex and leftContext to make the generated regexes dramatically shorter.

### CODE REVIEW

**Comment by mtlewis** [comment]
Updated to fix conflicts.  There's currently a [failing test in master](https://github.com/andyearnshaw/Intl.js/blob/master/tests/sanity.js#L57) which fails here, too.

**Comment by caridy** [comment]
This is looking good @mtlewis. What about inverting the default behavior? and just exposing a method that can be called to enable compliance with spec? This will also have to be called when running test262, but I can take care of that after you change this.

**Comment by mtlewis** [comment]
Wouldn't that constitute a breaking change, and therefore imply a major version bump?  It seems like the pragmatic way to get these improvements out to the largest group of people is to:

1. Take these changes as they are now, leaving cache/restore on by default and bumping the minor version, then
2. Switch off cache/restore by default, and bump the major version.

**Comment by caridy** [comment]
@mtlewis thanks for the PR, this is now merged... please try it and let us know :)

**Comment by mtlewis** [comment]
Fantastic!  Glad to hear it's merged - was a pleasure contributing :)

**Comment by caridy** [comment]
https://github.com/andyearnshaw/Intl.js/releases/tag/v1.2.5

**Pull request merged**
