### PR TITLE
Added Intl.complete to bower main

### PR DESCRIPTION
**Pull request by ollym**
Useful for build tools that rely on it

### CODE REVIEW

**Comment by andyearnshaw** [comment]
The main reason I've been reluctant to do this is I don't want to make it too easy for someone to reference the "complete" file because it sounds better.  I wouldn't like to be the guy sat on the train trying to browse a site that wants to download a 200KB (gzipped!) file on his mobile device over a 2G connection, just because the developer was too lazy to RTFM.

What build tools need this? Aren't they better off using NPM as a dependency manager?

**Comment by ollym** [comment]
@andyearnshaw I think then you need to add the locale-data folder to main because this library isn't usable without at least one of the locale files.

We're using a custom build system, similar to webpack / sprockets that resolves and pulls in bower dependencies based on the value of `main`.

**Comment by andyearnshaw** [comment]
Probably just `locale-data/jsonp` is needed then.  If you'd like to edit your pull request or submit another, I'll merge it.

**Comment by caridy** [comment]
:+1:

**Pull request merged**
