### PR TITLE
Removed non gregorian calendar data + update dependencies

### PR DESCRIPTION
**Pull request by swernerx**
In our current project we use the Intl-Polyfill which is super useful for i18n using React.

An issue we figured was that though we are only supporting European countries:

```
import 'intl/locale-data/jsonp/de-DE'
import 'intl/locale-data/jsonp/de-CH'
import 'intl/locale-data/jsonp/de-LU'
import 'intl/locale-data/jsonp/de-AT'
import 'intl/locale-data/jsonp/fr-LU'
import 'intl/locale-data/jsonp/fr-CH'
import 'intl/locale-data/jsonp/cs-CZ'
import 'intl/locale-data/jsonp/nl-NL'
```

we are loading a lot of data from non typical calendars in Europe e.g. persian, hebrew, indian, ...

Actually we saw a size drop from ~76 KB to 8 KB for each country we support when removing these calendars. Interestingly the readme mentions also that these calendars are not yet supported API-wise. So I assume that we can safely remove them for now and reduce page load times quite a bit (especially interesting for iOS which still needs the polyfill).

I also updated the CLDR data to v29 + regenerated all libraries and data files.

### CODE REVIEW

**Comment by caridy** [comment]
Hey @swernerx can you send the PR without all the build files? just the actual changes, and we will build it after the merge. Otherwise it is almost impossible to review it.

**Comment by swernerx** [comment]
The interesting part is in a single commit: https://github.com/andyearnshaw/Intl.js/pull/224/commits/6a1ab8762984e83e3b21fdb48fbfdb6b423c1d3b

**Comment by caridy** [comment]
@andyearnshaw what do you think about this? even though we explicitly called out in the readme that only gregorian is supported, we still have all the other calendars. I don't remember exactly the "why"! :)

**Comment by andyearnshaw** [comment]
I have no objections to removing the other calendars from the data (in fact it makes sense to do so).  They were left in because I did plan to implement other calendars eventually but never had a personal need for it, and I figured gzipping would eliminate a large chunk of the file size.

I'd still like to see other calendars supported, but have no time for it myself.  If someone were to submit a PR in the future, we'd have to add the data back in then.  Even then, it might be a good idea to make it optional.

**Comment by caridy** [comment]
Ok, I will take care of it.

**Comment by juandopazo** [comment]
While we do localize to locales that have their own calendars, we use the gregorian calendar for all of them at Yahoo. So I'm ok with this change.

**Comment by swernerx** [comment]
Thanks!

A new release would be very appreciated!

**Comment by caridy** [comment]
Just came back from vacation, it will take me a few days to get the stuff ready, the good news is that we have the polyfill service updated now :)

**Pull request merged**
