### PR TITLE
supporting short `month` format in most cases to match browser's behavior

### PR DESCRIPTION
**Pull request by caridy**
This matches FF and Chrome implementations. As a result, we get support these new entries:

```
Wednesday, December 19, 2012, 10:00:00 PM
Wednesday, Dec 19, 2012, 10:00:00 PM           // new entry

Wednesday, December 19, 2012
Wednesday, Dec 19, 2012           // new entry

December 19, 2012
Dec 19, 2012           // new entry

December 2012
Dec 2012           // new entry

December 19
Dec 19           // new entry
```

This does not come for free though, it increases the size of the data slightly, but not significant IMO, essentially it will increase each locale with:

```json
            {
                "weekday": "long",
                "month": "short",
                "day": "numeric",
                "year": "numeric",
                "hour": "numeric",
                "minute": "2-digit",
                "second": "2-digit",
                "pattern": "{weekday}, {month} {day}, {year}, {hour}:{minute}:{second}",
                "pattern12": "{weekday}, {month} {day}, {year}, {hour}:{minute}:{second} {ampm}"
            },
            {
                "weekday": "long",
                "month": "short",
                "day": "numeric",
                "year": "numeric",
                "pattern": "{weekday}, {month} {day}, {year}"
            },
            {
                "month": "short",
                "day": "numeric",
                "year": "numeric",
                "pattern": "{month} {day}, {year}"
            },
            {
                "month": "short",
                "year": "numeric",
                "pattern": "{month} {year}"
            },
            {
                "month": "short",
                "day": "numeric",
                "pattern": "{month} {day}"
            },
        ],
```

I will probably propose to drop the two first entries, at the end of the day, if you are going for the expanded date format, you probably don't care about short month since you're using long weekday, and even time, e.g.:

```
Wednesday, Dec 19, 2012, 10:00:00 PM
Wednesday, Dec 19, 2012
```

That will be sort of a middle ground where we will increase just few entries to support the minimum number of formats.

### CODE REVIEW

**Comment by caridy** [comment]
this PR is related to https://github.com/andyearnshaw/Intl.js/issues/65, and fixes https://github.com/andyearnshaw/Intl.js/issues/68 and https://github.com/andyearnshaw/Intl.js/issues/69, and partially solves https://github.com/andyearnshaw/Intl.js/issues/75

**Comment by caridy** [comment]
another alternative is to continue the work on https://github.com/andyearnshaw/Intl.js/issues/77

**Comment by ericf** [comment]
@caridy what's the gz size difference between the current and this new data for say `en-US`?

**Comment by okuryu** [comment]
Hmm.. #69 (and #88) seems not to be fixed by this change, am I missing something?

```sh
$ npm install
$ $(npm bin)/grunt update-cldr-data
$ $(npm bin)/grunt cldr
$ $(npm bin)/grunt
$ node -v
> require("./index")
{ __localeSensitiveProtos: 
   { Number: { toLocaleString: [Function] },
     Date: 
      { toLocaleString: [Function],
        toLocaleDateString: [Function],
        toLocaleTimeString: [Function] } },
  default: [Circular] }
> new Intl.DateTimeFormat("ja",{year:"numeric",month:"long",day:"numeric",weekday:"long"}).format(new Date())
'2015年3月月28日(土曜日)'
```

Expected result as follows (Chrome's result).

```js
> new Intl.DateTimeFormat("ja",{year:"numeric",month:"long",day:"numeric",weekday:"long"}).format(new Date())
"2015年3月28日土曜日"
```

**Comment by caridy** [comment]
@okuryu this is really not much about the short variation (yes, I have a patch in there to add few shorts variations, but this is really about the new build process so we can start making significant changes again.

To be more specific, we want to use CLDR data to support all variations, by simply using CLDR data directly instead of a computed portion of it. Here you can see the big difference from one locale to another:

https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/en-001/ca-gregorian.json#L309-L349
https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/ja/ca-gregorian.json#L300-L345

As you can see, they don't have the same entries, instead, we just need to update our computations, to pick up the right variation from the list available instead of a predefined, prebuild subset.

This PR seems to be complete now, although functional tests (saucelab tests are failing, I might need help with that since I don't have too much time before going on vacation).

**Comment by mjackson** [comment]
I'm +1 for whatever we need to do to make Intl.js act like browsers do.

**Comment by caridy** [comment]
fixes https://github.com/andyearnshaw/Intl.js/issues/77

**Comment by caridy** [comment]
fixes https://github.com/andyearnshaw/Intl.js/issues/75

**Comment by caridy** [comment]
fixes https://github.com/andyearnshaw/Intl.js/issues/69

**Comment by caridy** [comment]
fixes https://github.com/andyearnshaw/Intl.js/issues/68

**Comment by caridy** [comment]
@juandopazo is working on the saucelab failures which is the only missing bit at this point for rc1 to be released.

**Comment by caridy** [comment]
We were able to test saucelabs manually, we just need to figure what to do with the travis integration that is failing today. I will merge this and figure that in a different PR.

**Comment by longlho** [comment]
ping @caridy it'd be awesome if u can merge this :+1: thanks!

**Comment by redonkulus** [comment]
Thanks @andyearnshaw. When can we expect it to be published?

**Comment by kate2753** [comment]
@caridy it seems that there's missing src file `src\cldr.js`. With latest source code `grunt build` fails with this error

```
Running "bundle_jsnext:dest" (bundle_jsnext) task
INFO: Using a global wrapper module for "src/main.js", exporting namespace "IntlPolyfill"
Fatal error: Error writing bundle in "dist/Intl.js": Error: missing module import from ./core for path: ./cldr
```

**Comment by marcelombc** [comment]
Can you please release a new version/tag with this fix? Thank you.

**Comment by Coobaha** [comment]
publish it please :+1:

**Comment by pgherveou** [comment]
yop a new npm version with these fixes would be great!

**Comment by caridy** [comment]
1.0.0-rc-1 is in NPM, help us to test it...

**Comment by pgherveou** [comment]
works fine for me, thks a lot

**Comment by bcecchinato** [comment]
Issue https://github.com/yahoo/ember-intl/issues/101 is partially fixed (works fine on Chrome and IE11, not on IE9 and IE10).

Regards,

**Comment by caridy** [comment]
@bcecchinato thanks for the report. Can you give us more details about the issue wiht IE9/IE10?

**Comment by bcecchinato** [comment]
@caridy : When using the following format for date : 
```js
export default {
    'date-style': {
      day:  '2-digit',
      month:  '2-digit',
      year:  'numeric'
    }
};
```

Day and month are on one digit when lower than 10. For instance, 15/06/2015 would be written 15/6/2015. The issue was also occurring on Chrome and IE11, since the 1.0.0-rc-1 it seems to be fixed.

Regards,

**Comment by caridy** [comment]
can you open an issue for that so we can try to fix it. I have some suspicious about it, but I will have to dig in.

**Comment by bcecchinato** [comment]
@caridy Done in issue #105 :)

**Pull request merged**
