### PR TITLE
Changed path to core.js

### PR DESCRIPTION
**Pull request by PeterOrneholm**
From what I can see the path to core.js is wrong. The lib folder does not exists, but src do.

### CODE REVIEW

**Comment by caridy** [comment]
@PeterOrneholm, lib will be generating during the build process before pushing it to npm.

**Comment by PeterOrneholm** [comment]
@caridy Thanks! I was obviously to quick on this one.

My scenario was that I referenced the package using jspm, and by default the jspm registry (http://kasperlewau.github.io/registry/#/?q=intl) points to the GitHub-version which does not have the lib folder, and that's when I got the error. When I know explicitly references the NPM version it works fine. I'll make a pull request to the jspm registry so that npm becomes the default choice.

**Comment by caridy** [comment]
I can talk to @guybedford about this, but I suspect what it requires is the correct entries in package.json to point to the ES modules source.

**Comment by PeterOrneholm** [comment]
Yes, but now the jspm registry points to npm, so it should work.
https://github.com/jspm/registry/pull/957

**Pull request closed without merging**
